apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-test
  namespace: testapp
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: <docker-hub-username>/fastapi-test:latest
