apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-test
  namespace: testapp
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: <docker-hub-username>/fastapi-test:latest
        # add port configuration
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: testapp
spec:
  selector:
    app: api
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi
  namespace: testapp
spec:
  ingressClassName: nginx
  rules:
  - host: k8s-tutorial.local
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: fastapi
            port:
              number: 8000
